### ISSUE TITLE
app.js seems not working on production build

### ISSUE THREAD

**Issue by LouRaul** [scottishstoater/eleventy-web-starter#11]
Hi! 👋
(First of all, thanks for this template, it's super useful for a newbie like me)

I'm trying to install alpine.js using NPM, and although it's working locally (npm start) it doesn't work when deploying on Netlifly (NPM run build)

This is what I did:
1. I install Alpine.js using `npm i alpinejs`
2. I added `import 'alpinejs'` to  src/_assets/scripts/site.js (first line)

These are the things I checked that make me think maybe app.js is not loading on production
- Show/hide behaviors are not working
- Console.log message is not loading
- I can't access /static/app.bundled.js (Netlify screen file not found)
- I also checked https://webstarter.chriscollins.me/ with same results

Is it possible there is a problem when building the  app.bundled.js? 

Site on Production: https://baterias-gesell.netlify.app/
Repo: https://github.com/LouRaul/baterias-gesell

Thnaks!

**Comment by chrissy-dev** [comment]
Hey @LouRaul,

Thanks for flagging this. 

This appears to be a strange recent issue with Netlify and applying the `.gitignore` contents to the `/dist` folder. 

There's a [post on Netlify Community about this](https://community.netlify.com/t/dont-apply-gitignore-rules-to-the-publish-directory/21244/10) and although they've made changes, I'm still seeing this behaviour. 

I've pushed an update to directly bundle the script into `/dist` on production and Netlify is sucessfully uploading the bundle now. 

Once again, thanks for taking the time to flag this 👍

**Comment by chrissy-dev** [comment]
I've opened a PR for your repo to update the project 😄

**Comment by LouRaul** [comment]
Thanks for doing this!
Your template is amazing!
