### ISSUE TITLE
Version 2 Roadmap

### ISSUE THREAD

**Issue by chrissy-dev** [scottishstoater/eleventy-web-starter#18]
Back in 2018 the project goal of JAMStack Web Starter was to create a simple project structure that tied Eleventy and an opinionated asset pipeline together. The core pillars (Eleventy, Tailwind, Webpack and Post CSS) all worked together using simple commands but contained the absolute minimal configuration. 

Although I still firmly believe the best boilerplate is minimal with solid foundations there's a few things I'll be changing in version 2. These changes are taking into account the emails and questions I've been asked over the last couple of years about the project. 

### Tailwind & CSS

I'm a big Tailwind fan. Some of the Twitter fanboys have questionable strong opinions on it, I'm not one of them. I believe it has it's place within the web eco-system but I don't think anyone should be forced to use it or degraded for not using it/using it. It's an optional tool at the end of the day. 

- Documented support for adding Tailwind CSS v2+ to the project but not by default. 
- Make CSS3 (combined with Post CSS) a first class citizen. 

### Javascript

I don't dislike Webpack but it's probably overkill for a project of this size. I still believe the ability to bundle ES6 modules is a core functionality of a boilerplate, especially a Javascript based one where the developer is most likely familiar with the eco-system. 

- Use a smaller and more efficient Javascript bundler in place of Webpack, perhaps [esbuild](https://github.com/evanw/esbuild).

### Eleventy 

It's evident there's some additional foundations within the Eleventy boilerplate that would be useful and are likely required most of the time.

- Support for [eleventy-img](https://www.11ty.dev/docs/plugins/image/) out the box.
- Tag support out the box.
- Sample collection in the form of a blog utilising tags.
- Support for storing assets alongside it's associated collection files. (eg, images from a blog post live in the same folder as the markdown file).

### Misc
- Basic server worker support.
- Slight changes to the project structure.

### Notes
- Major breaking change. 

I'll start scoring these off as I work through them. All work will be available on a v2 branch while it's getting worked on.

**Comment by ineptian** [comment]
Who cares about the twitter fan boys!? In all honesty though I have used so many frameworks and tailwind is easily the best. This starter, also one of the best. Thanks for work!
