### ISSUE TITLE
How to get ELEVENTY_ENV variable set to production

### ISSUE THREAD

**Issue by ineptian** [scottishstoater/eleventy-web-starter#22]
Thanks for the awesome starter. I have my site deployed to netlify, and I set my NODE_ENV variable to production on netlify, but for some reason this code for the open graph image is still not printing the site url before the image.
```
<meta property="og:image" content="{% if env == 'production' %}{{ site.url }}{% endif %}{% if featured_image  %}{{ featured_image }}{% else %}{{ site.meta_data.default_social_image }}{% endif %}" />
```
Any ideas why? Do I need to set my elevent_env to production in netlify as well?

Thanks!

**Comment by chrissy-dev** [comment]
Ahh, that's a bug inhertied from an older version. The `env` variable now lives in `site.env`. 

Change line 56 in `src/_includes/head.njk` to: 

```html
<meta property="og:image" content="{% if site.env == 'production' %}{{ site.url }}{% endif %}{% if featured_image  %}{{ featured_image }}{% else %}{{ site.meta_data.default_social_image }}{% endif %}" />
```

Thanks for flagging.

**Comment by ineptian** [comment]
Do I still need to set the ELEVENT_ENV variable in netlify? Thanks for the reply!

**Comment by chrissy-dev** [comment]
No, it's set on the build script in `package.json`.
