### ISSUE TITLE
node_env etc on windows (and others)

### ISSUE THREAD

**Issue by jshwlkr** [scottishstoater/eleventy-web-starter#32]
I think you'll want to use something like https://www.npmjs.com/package/cross-env to make sure env vars are cross-platform.

**Comment by chrissy-dev** [comment]
@jshwlkr Ouch! That's what I get for only testing on Unix. I'll add this in, thanks.

**Comment by jshwlkr** [comment]
No prob!

**Comment by chrissy-dev** [comment]
@jshwlkr Closing this in favour of #41. Thanks again :)
