### ISSUE TITLE
Browsersync not working

### ISSUE THREAD

**Issue by ineptian** [scottishstoater/eleventy-web-starter#36]
```
npm run start
```
Open localhost:8080

Make a change to index.njk and save

Browsersync says reloading browsers, but it doesnt actually reload the browser.

If I refresh the changes are shown.

On windows.

**Comment by chrissy-dev** [comment]
Hey @ineptian, did you manage to get this working?

**Comment by ineptian** [comment]
@chrissy-dev yes sorry. Noticed what it was like 30 seconds after posting this. It was my fault nothing at all related to your project. I could be blind but I couldn't see how to delete this just close it. Sorry for cluttering the issues panel!
