### ISSUE TITLE
Netlify Builds Failing

### ISSUE THREAD

**Issue by EdenKupe** [scottishstoater/eleventy-web-starter#4]
Hey there!

Thanks so much for this starter kit, it's awesome! However, either when clicking on the "Deploy to Netlify" button or when cloning this repo and trying to upload to a new Netlify instance, I get the following error:

```
1:58:06 AM: Failing build: Failed to build site
1:58:06 AM: failed during stage 'building site': Deploy directory '_site' does not exist
```

Any idea what's happening here? I've also received other errors when experimenting which hinted that Eleventy might not be installing correctly?

Thanks in advance!

**Comment by chrissy-dev** [comment]
Hey @EdenKupe, 

Thanks for reporting this. You are correct, the repo doesn't provide Netlify with any configuration and when using the big button it defaults to the wrong output and build command. I've fixed this now by adding a `netlify.toml` file in the root of the project. Thanks for flagging this!

If you have a project already working on and don't want to re-clone the repo you can edit your Netlify settings directly to work with the project. 

1. Go to Netlify and select your site
2. Go to Settings > Build & Deploy 
3. Under the build settings hit "Edit settings"
4. Use the following values:
	- Base directory: Leave this blank
	- Build command: `npm run build`
	- Publish directory: `dist`
5. Go to Deploys back in the top menu 
6. Tigger a new deploy

Apologies for the missing config, hope this help and gets you back on track.
