### ISSUE TITLE
Updating to tailwind 1.4 (purge built in)

### ISSUE THREAD

**Issue by m1chaeljmk** [scottishstoater/eleventy-web-starter#7]
Tailwind 1.4 has Purge built in... will this affect anything if I use this version of the web starter and then update tailwind after?

https://github.com/tailwindcss/tailwindcss/releases/tag/v1.4.0

**Comment by chrissy-dev** [comment]
@mk0r Excellent! It shouldn't. I'll update the repo shortly. 

You can update Tailwind to the latest version and then remove code that isn't required anymore:
- Remove dependency for `@fullhuman/postcss-purgecss` in `package.json`.
- Remove lines 1-8 and 14-16 in the `postcss.config.js`. 
- Add the purge option below to your `tailwind.config.js`.

```js
 purge: process.env.NODE_ENV === 'production' ? {
    enabled: true,
    content: ['dist/**/*.html', 'dist/**/*.js'],
  } : {}
```

**Comment by chrissy-dev** [comment]
@mk0r This is now released. Thank you.
